WebBanHang/WebBanHang/Controllers/Backend/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBanHang.Controllers.Backend
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View("~/Views/Backend/Dashboard/Index.cshtml");
        }
    }
}

WebBanHang/WebBanHang/Controllers/Backend/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanHang.EF;

//Add The following Namespaces to the project
using Microsoft.Azure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob; // Multipart

namespace WebBanHang.Controllers.Backend
{
    public class ProductsController : Controller
    {
        private QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        public string StorageConnectionString = "DefaultEndpointsProtocol=https;AccountName=azurestudentsdiag959;AccountKey=yYLvvu+cHBGK/sBLIvbYkVzE/VBS+z5Tw4K5komw2ybyvFYIV7ilKtYZnfa7rYQwUvTSrmFniX9QNrLyq9y3sQ==;EndpointSuffix=core.windows.net";

        // GET: Products
        public ActionResult Index()
        {
            return View("~/Views/Backend/Products/Index.cshtml", db.products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            products products = db.products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View("~/Views/Backend/Products/Create.cshtml");
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "id,product_code,product_name,description,standard_cost,list_price,target_level,reorder_level,minimum_reorder_quantity,quantity_per_unit,discontinued,category,image")] products products,
            HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                // Xử lý file: lưu file vào thư mục UploadedFiles/ProductImages
                string _FileName = "";
                // Di chuyển file vào thư mục mong muốn
                if (image != null && image.ContentLength > 0)
                {
                    _FileName = Path.GetFileName(image.FileName);                   // QRCode_NenTangUrl.png
                    string _FileNameExtension = Path.GetExtension(image.FileName);  // .png
                    if ((_FileNameExtension == ".png"
                        || _FileNameExtension == ".jpg"
                        || _FileNameExtension == ".jpeg"
                        ) == false)
                    {
                        return View(String.Format("File có đuôi {0} không được chấp nhận. Vui lòng kiểm tra lại!", _FileNameExtension));
                    }

                    // Upload file lên thư mục Web Server (VPS)
                    string uploadFolderPath = Server.MapPath("~/UploadedFiles/ProductImages");
                    if (Directory.Exists(uploadFolderPath) == false) // Nếu thư mục cần lưu trữ file upload không tồn tại (chưa có) => Tạo mới
                    {
                        Directory.CreateDirectory(uploadFolderPath);
                    }

                    // Copy file ảnh vào Thư mục UploadFiles/ProductImages trên Server
                    //string _path = Path.Combine(uploadFolderPath, _FileName);
                    //image.SaveAs(_path);

                    // Lưu thông tin đường dẫn vào Database
                    products.image = image.FileName;

                    // Update file lên thư mục Storage Azure
                    // Create Reference to Azure Storage Account
                    String strorageconn = this.StorageConnectionString;
                    CloudStorageAccount storageacc = CloudStorageAccount.Parse(strorageconn);

                    //Create Reference to Azure Blob
                    CloudBlobClient blobClient = storageacc.CreateCloudBlobClient();

                    //The next 2 lines create if not exists a container named "democontainer"
                    CloudBlobContainer container = blobClient.GetContainerReference("democontainer");
                    container.CreateIfNotExists();

                    //The next 7 lines upload the file test.txt with the name DemoBlob on the container "democontainer"
                    CloudBlockBlob blockBlob = container.GetBlockBlobReference(_FileName);
                    blockBlob.UploadFromStream(image.InputStream);
                }

                // Lưu dữ liệu
                db.products.Add(products);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(products);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            products products = db.products.Find(id); // SELECT * FROM products WHERE id = 601
            if (products == null)
            {
                return HttpNotFound();
            }
            ViewBag.Product = products;
            return View("~/Views/Backend/Products/Edit.cshtml", products);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,product_code,product_name,description,standard_cost,list_price,target_level,reorder_level,minimum_reorder_quantity,quantity_per_unit,discontinued,category")] products products, string image_oldFile, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                string uploadFolderPath = Server.MapPath("~/UploadedFiles/ProductImages");

                if (image == null) // Nếu không cập nhật file (không chọn file)
                {
                    // Giữ nguyên giá trị của tên file trong cột `image`
                    products.image = image_oldFile;
                }
                else // Người ta có chọn file ảnh mới
                {
                    // 1. Xóa file ảnh cũ (để tránh rác)
                    // ~/UploadedFiles/ProductImages/ASP.NET_CodeXuLyDangKy.png -> đường dẫn file ảnh cũ
                    string filePathAnhCu = Path.Combine(uploadFolderPath, (products.image == null ? "" : products.image));
                    if (System.IO.File.Exists(filePathAnhCu))
                    {
                        System.IO.File.Delete(filePathAnhCu);
                    }

                    // 2. Upload file ảnh mới
                    // Xử lý file: lưu file vào thư mục UploadedFiles/ProductImages
                    string _FileName = "";
                    // Di chuyển file vào thư mục mong muốn
                    if (image.ContentLength > 0)
                    {
                        _FileName = Path.GetFileName(image.FileName);                   // QRCode_NenTangUrl.png
                        string _FileNameExtension = Path.GetExtension(image.FileName);  // .png
                        if ((_FileNameExtension == ".png"
                            || _FileNameExtension == ".jpg"
                            || _FileNameExtension == ".jpeg"
                            ) == false)
                        {
                            return View(String.Format("File có đuôi {0} không được chấp nhận. Vui lòng kiểm tra lại!", _FileNameExtension));
                        }

                        if (Directory.Exists(uploadFolderPath) == false) // Nếu thư mục cần lưu trữ file upload không tồn tại (chưa có) => Tạo mới
                        {
                            Directory.CreateDirectory(uploadFolderPath);
                        }

                        string _path = Path.Combine(uploadFolderPath, _FileName);
                        image.SaveAs(_path);
                    }
                    // Lưu tên file vào database
                    products.image = _FileName;
                }

                /* UPDATE products
                 * SET product_code = 'P3333',
                 *      product_name = 'DELL 333'
                 * WHERE id = 603
                 */
                db.Entry(products).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(products);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            products products = db.products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            ViewBag.Product = products;
            return View("~/Views/Backend/Products/Delete.cshtml", products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            products products = db.products.Find(id);
            db.products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHang/WebBanHang/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.EF;

namespace WebBanHang.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        // GET
        public ActionResult ProductDetail(int idProduct)
        {
            products product = null;
            // Lấy dữ liệu Sản phẩm bởi idProduct
            using (QuanLyBanHangEntities context = new QuanLyBanHangEntities())
            {
                product = context.products.Where(p => p.id == idProduct).FirstOrDefault();
            }

            // Truyền dữ liệu từ Controller sang View
            ViewBag.SanPham = product;

            return View();
        }
    }
}

WebBanHang/WebBanHang/Views/Backend/Products/Create.cshtml
@model WebBanHang.EF.products

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Backend/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2" for="product_code">Mã sản phẩm</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="product_name">Tên sản phẩm</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.standard_cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.standard_cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.standard_cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.list_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.list_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.list_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.target_level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.target_level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.target_level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reorder_level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reorder_level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reorder_level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.minimum_reorder_quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.minimum_reorder_quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minimum_reorder_quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity_per_unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity_per_unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity_per_unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.discontinued, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.discontinued, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.discontinued, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="image">Hình đại diện sản phẩm</label>
            <div class="col-md-10">
                <input type="file" name="image" id="image"/>
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu Sản phẩm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebBanHang/WebBanHang/Views/Backend/Products/Delete.cshtml
@model WebBanHang.EF.products

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Backend/Shared/_Layout.cshtml";
}

<h2>Xóa Sản phẩm</h2>

<h3>Bạn có chắc chắn muốn xóa Sản phẩm này không?</h3>
<div>
    <h4>Sản phẩm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.standard_cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.standard_cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.target_level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.target_level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reorder_level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reorder_level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.minimum_reorder_quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minimum_reorder_quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity_per_unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity_per_unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.discontinued)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.discontinued)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
            @if (String.IsNullOrEmpty(ViewBag.Product.image))
            {
                <img class="bd-placeholder-img card-img-top img-thumbnail" style="width: 100px; height: 100px;" src="~/Content/img/no-photo.png">
            }
            else
            {
                <img class="bd-placeholder-img card-img-top img-thumbnail" style="width: 100px; height: 100px;" src="~/UploadedFiles/ProductImages/@ViewBag.Product.image">
            }
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Products", FormMethod.Post, new { id = "form-delete-product", @class = "btn btn-danger" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" id="btn-delete-product" />
        </div>
    }
    | @Html.ActionLink("Quay về Danh sách Sản phẩm", "Index")
</div>

@section scripts {
<script>
    $(document).ready(function () {
        $('#form-delete-product').submit(function (e) {
            e.preventDefault(); // Ngăn không cho gởi dữ liệu đến Server -> để mình tự xử lý

            // Sử dụng SweetAlert để hiển thị popup confirm
            Swal.fire({
                title: 'Bạn có chắc chắn thực hiện thao tác này không?',
                text: "Không thể phục hồi dữ liệu đã xóa!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Đồng ý, tôi xác nhận Xóa!'
            }).then((result) => {
                if (result.value) { // Nếu nhấn Yes
                    // Tiếp tục submit
                    $.ajax({
                        type: "POST",
                        url: "/admin/products/delete/@ViewBag.Product.id",
                        success: function () {
                            // Nếu thành công -> điều hướng về trang Danh sách
                            location.href = "/admin/products";
                        },
                        error: function () {
                            // Nếu thất bại -> hiển thị popup thông báo
                            Swal.fire({
                                icon: 'error',
                                title: 'Oops...',
                                text: 'Có lỗi xảy ra! Sản phẩm đang được sử dụng, không được phép xóa!',
                                footer: '<a href="https://nentang.vn">Click vào đây để gọi hỗ trợ</a>'
                            });
                        }
                    });
                }
            })
        });
    });
</script>
}

WebBanHang/WebBanHang/Views/Backend/Products/Details.cshtml
@model WebBanHang.EF.products

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Backend/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>products</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.standard_cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.standard_cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.target_level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.target_level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reorder_level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reorder_level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.minimum_reorder_quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minimum_reorder_quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity_per_unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity_per_unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.discontinued)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.discontinued)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebBanHang/WebBanHang/Views/Backend/Products/Edit.cshtml
@model WebBanHang.EF.products

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Backend/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>products</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        <label class="control-label col-md-2" for="product_code">product_code</label>
        <div class="col-md-10">
            <input type="text" name="product_code" id="product_code" value="@ViewBag.Product.product_code" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.product_code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.product_code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.product_code, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.standard_cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.standard_cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.standard_cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.list_price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.list_price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.list_price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.target_level, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.target_level, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.target_level, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.reorder_level, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.reorder_level, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.reorder_level, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.minimum_reorder_quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.minimum_reorder_quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.minimum_reorder_quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.quantity_per_unit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quantity_per_unit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.quantity_per_unit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.discontinued, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.discontinued, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.discontinued, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.category, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="image">Hình đại diện sản phẩm</label>
        <div class="col-md-10">
            @if (String.IsNullOrEmpty(ViewBag.Product.image))
            {
                <img class="bd-placeholder-img card-img-top img-thumbnail" style="width: 100px; height: 100px;" src="~/Content/img/no-photo.png">
            }
            else
            {
                <img class="bd-placeholder-img card-img-top img-thumbnail" style="width: 100px; height: 100px;" src="~/UploadedFiles/ProductImages/@ViewBag.Product.image">
            }

            <input type="hidden" name="image_oldFile" value="@ViewBag.Product.image" />
            <input type="file" name="image" id="image" />
            @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}